name: radx-kg

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.10
  - jupyterlab
  - jupyter-offlinenotebook
  - jupyterlab_widgets
  - ipywidgets
  - pandas
  - levenshtein
  - titlecase
  - tqdm
  - black

