name: radx-kg

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.10
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - pandas
  - pyarrow
  - levenshtein
  - titlecase
  - tqdm
  - matplotlib
  - seaborn
  - scikit-learn
  - python-dotenv
  - black
  - fake-useragent
  - papermill
  - py2neo=2021.2.3
  - monotonic=1.5
  - openjdk=17.0.8
  - python-dotenv=1.0.0
  - ipycytoscape
  - plotly

